# Generated by Django 5.2.8 on 2025-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('reference_hash', models.CharField(max_length=256)),
                ('device_id', models.CharField(max_length=100)),
                ('os_info', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TamperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
                ('detected_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
