# Generated by Django 5.2.8 on 2025-11-07 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appverification',
            name='is_valid',
        ),
        migrations.AlterField(
            model_name='appverification',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appverification',
            name='os_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appverification',
            name='reference_hash',
            field=models.CharField(default='unknown_hash', max_length=256),
        ),
        migrations.AlterField(
            model_name='tamperlog',
            name='details',
            field=models.TextField(default='No details'),
        ),
        migrations.AlterField(
            model_name='tamperlog',
            name='detected_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
