# Generated by Django 5.2.8 on 2025-11-08 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_remove_appverification_is_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamperlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='tamperlog',
            name='detected_time',
        ),
        migrations.AddField(
            model_name='tamperlog',
            name='issue',
            field=models.TextField(default='defoult123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamperlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tamperlog',
            name='app_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tamperlog',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
    ]
