# Generated by Django 5.2.8 on 2025-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0003_remove_tamperlog_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appverification',
            name='last_checked',
        ),
        migrations.AddField(
            model_name='appverification',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appverification',
            name='last_verified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appverification',
            name='reference_hash',
            field=models.CharField(max_length=256),
        ),
    ]
