# Generated by Django 5.2.8 on 2025-11-08 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0005_registeredapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamperlog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tamperlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
